// Inventory — the Asset Registry data
// Categories form a taxonomy. Assets carry typed attributes per vertical template.

window.INVENTORY = {
  categories: [
    { id: "cat_watches", name: "Watches", parent: null, vertical: "watch", count: 6 },
    { id: "cat_jewellery", name: "Jewellery", parent: null, vertical: "jewellery", count: 4 },
    { id: "cat_instruments", name: "Instruments", parent: null, count: 5 },
    { id: "cat_guitars", name: "Guitars", parent: "cat_instruments", vertical: "guitar", count: 4 },
    { id: "cat_audio", name: "Audio", parent: "cat_instruments", count: 1 },
    { id: "cat_clothing", name: "Clothing & shoes", parent: null, vertical: "clothing", count: 18 },
    { id: "cat_suits", name: "Suits", parent: "cat_clothing", vertical: "clothing", count: 6 },
    { id: "cat_shoes", name: "Shoes", parent: "cat_clothing", vertical: "clothing", count: 8 },
    { id: "cat_outerwear", name: "Outerwear", parent: "cat_clothing", vertical: "clothing", count: 4 },
    { id: "cat_home", name: "Home", parent: null, count: 24 },
    { id: "cat_furniture", name: "Furniture", parent: "cat_home", vertical: "furniture", count: 9 },
    { id: "cat_glassware", name: "Glassware", parent: "cat_home", vertical: "glassware", count: 8 },
    { id: "cat_porcelain", name: "Porcelain", parent: "cat_home", vertical: "porcelain", count: 4 },
    { id: "cat_lighting", name: "Lighting", parent: "cat_home", count: 3 },
    { id: "cat_art", name: "Art", parent: null, vertical: "art", count: 5 },
    { id: "cat_appliances", name: "Appliances & systems", parent: null, count: 38 },
    { id: "cat_vehicles", name: "Vehicles", parent: null, vertical: "vehicle", count: 2 },
  ],
  collections: [
    {
      id: "col_insurable", name: "Insurable — high value",
      desc: "Assets recommended for the schedule on the Hiscox policy",
      members: ["ast_rolex", "ast_ap", "ast_les_paul", "ast_d28", "ast_picasso", "ast_eames"],
      visibility: "Principal",
      totalValue: 248500,
      currency: "GBP",
    },
    {
      id: "col_wardian_main", name: "Wardian — primary residence",
      desc: "Everything kept at the London apartment",
      members: ["ast_rolex", "ast_ap", "ast_les_paul", "ast_d28", "ast_eames", "ast_riedel", "ast_meissen", "ast_brioni"],
      visibility: "Operational",
      totalValue: null,
    },
    {
      id: "col_seasonal", name: "Seasonal · winter rotation",
      desc: "Coats, wool suits, gloves stored in Wardian",
      members: ["ast_brioni", "ast_loro"],
      visibility: "Operational",
    },
    {
      id: "col_estate", name: "Estate planning — significant",
      desc: "Pieces flagged for succession review",
      members: ["ast_rolex", "ast_ap", "ast_picasso", "ast_d28"],
      visibility: "Principal",
      totalValue: 198500,
      currency: "GBP",
    },
    {
      id: "col_repair", name: "Currently with vendor",
      desc: "Watches at service, suits at tailor, art on loan",
      members: ["ast_jlc"],
      visibility: "Operational",
    },
  ],
  // The unified Asset registry
  assets: [
    // ────── Watches ──────
    {
      id: "ast_rolex",
      title: "Rolex Submariner Date",
      maker: "Rolex",
      category: "cat_watches",
      vertical: "watch",
      mode: "unique",
      tracking: { quantity: 1 },
      location: { propId: "wardian", roomId: "r2", sub: "Safe · top shelf", custody: "with-owner" },
      condition: "Excellent",
      status: "Owned",
      acquired: "2019-06-12",
      acquisitionCost: 8950, currency: "GBP",
      value: { current: 11200, source: "Bob's Watches · May 2026", insured: 12500 },
      tags: ["heirloom", "everyday-wear"],
      collections: ["col_insurable", "col_wardian_main", "col_estate"],
      photo: { fill: "linear-gradient(140deg,#1A2436 0%,#2C3E5C 60%,#4B6483 100%)", icon: "Watch" },
      docs: 3,
      timelineCount: 7,
      attrs: {
        Model: "126610LN",
        Serial: "Z789214B",
        Year: "2019",
        Material: "Oystersteel",
        Movement: "Calibre 3235 · automatic",
        "Box & papers": "Yes",
        "Country of manufacture": "Switzerland",
      },
      completeness: 0.94,
    },
    {
      id: "ast_ap",
      title: "Audemars Piguet Royal Oak",
      maker: "Audemars Piguet",
      category: "cat_watches",
      vertical: "watch",
      mode: "unique",
      location: { propId: "wardian", roomId: "r2", sub: "Safe · top shelf", custody: "with-owner" },
      condition: "Mint",
      status: "Owned",
      acquired: "2022-03-30",
      acquisitionCost: 36500, currency: "GBP",
      value: { current: 58000, source: "Watchfinder · April 2026", insured: 65000 },
      tags: ["dress", "investment"],
      collections: ["col_insurable", "col_wardian_main", "col_estate"],
      photo: { fill: "linear-gradient(140deg,#2C2E33 0%,#52555E 60%,#7A7E89 100%)", icon: "Watch" },
      docs: 5,
      timelineCount: 4,
      attrs: {
        Model: "15510ST.OO.1320ST.02",
        Serial: "K-44210",
        Year: "2022",
        Material: "Stainless steel",
        Movement: "Calibre 4302",
        "Box & papers": "Yes",
      },
      completeness: 0.98,
    },
    {
      id: "ast_jlc",
      title: "Jaeger-LeCoultre Reverso",
      maker: "Jaeger-LeCoultre",
      category: "cat_watches",
      vertical: "watch",
      mode: "unique",
      location: { propId: "wardian", roomId: null, sub: "—", custody: "with-vendor", custodyParty: "JLC Service · London" },
      condition: "Service",
      status: "Owned",
      acquired: "2015-09-04",
      acquisitionCost: 6200, currency: "GBP",
      value: { current: 6800, source: "Estimate", insured: 8500 },
      tags: ["dress", "service-due"],
      collections: ["col_repair"],
      photo: { fill: "linear-gradient(140deg,#3F3B33 0%,#7A6B53 60%,#A8907A 100%)", icon: "Watch" },
      docs: 3,
      timelineCount: 9,
      attrs: { Model: "Reverso Classique", Serial: "Q2548520", Year: "2015", Material: "Stainless steel" },
      completeness: 0.78,
    },
    // ────── Guitars ──────
    {
      id: "ast_les_paul",
      title: "Gibson Les Paul Standard '59 Reissue",
      maker: "Gibson Custom",
      category: "cat_guitars",
      vertical: "guitar",
      mode: "unique",
      location: { propId: "wardian", roomId: "r3", sub: "Studio rack · A1", custody: "with-owner" },
      condition: "Excellent",
      status: "Owned",
      acquired: "2018-11-20",
      acquisitionCost: 5400, currency: "GBP",
      value: { current: 6800, source: "Reverb median · April 2026", insured: 7500 },
      tags: ["favourite", "fragile"],
      collections: ["col_insurable", "col_wardian_main"],
      photo: { fill: "linear-gradient(140deg,#4A1A0E 0%,#7A2E1B 60%,#A8523A 100%)", icon: "Guitar" },
      docs: 2,
      timelineCount: 5,
      attrs: {
        Maker: "Gibson Custom",
        Model: "Les Paul Standard '59 Reissue",
        Year: "2018",
        Serial: "98223",
        Finish: "Iced Tea Burst",
        "Body wood": "Mahogany / Maple cap",
        "Pickup configuration": "Burstbucker 1 + 2",
        "Country of manufacture": "USA",
        "Case included": "Yes — original",
      },
      completeness: 0.91,
    },
    {
      id: "ast_d28",
      title: "Martin D-28 Authentic 1937",
      maker: "C. F. Martin",
      category: "cat_guitars",
      vertical: "guitar",
      mode: "unique",
      location: { propId: "wardian", roomId: "r3", sub: "Studio rack · A2", custody: "with-owner" },
      condition: "Excellent",
      status: "Owned",
      acquired: "2020-08-04",
      acquisitionCost: 7800, currency: "GBP",
      value: { current: 9200, source: "Vintage Guitar · April 2026", insured: 10500 },
      tags: ["favourite"],
      collections: ["col_insurable", "col_wardian_main", "col_estate"],
      photo: { fill: "linear-gradient(140deg,#3A2918 0%,#6B4A2A 60%,#8C6B45 100%)", icon: "Guitar" },
      docs: 2,
      timelineCount: 3,
      attrs: { Maker: "C. F. Martin", Model: "D-28 Authentic 1937", Year: "2020", Serial: "M-2244011" },
      completeness: 0.86,
    },
    // ────── Glassware ──────
    {
      id: "ast_riedel",
      title: "Riedel Sommeliers · Bordeaux Grand Cru",
      maker: "Riedel",
      category: "cat_glassware",
      vertical: "glassware",
      mode: "grouped-quantity",
      tracking: { quantity: 8, originalQty: 12, lost: 4 },
      location: { propId: "wardian", roomId: "r4", sub: "Cabinet 2 · shelf 1", custody: "with-owner" },
      condition: "Good",
      status: "Owned",
      acquired: "2021-12-18",
      acquisitionCost: 720, currency: "GBP",
      value: { current: 640, source: "Replacement cost", insured: null },
      tags: ["fragile"],
      collections: ["col_wardian_main"],
      photo: { fill: "linear-gradient(140deg,#E8E4D8 0%,#C7BDA8 60%,#A89B82 100%)", icon: "Glass" },
      docs: 1,
      timelineCount: 4,
      attrs: { Maker: "Riedel", "Line or pattern": "Sommeliers · Bordeaux Grand Cru", Material: "Lead-free crystal", "Capacity ml": "860", "Set size": "12 (4 lost)", "Handmade": "Yes", "Dishwasher safe": "No" },
      completeness: 0.74,
    },
    // ────── Porcelain ──────
    {
      id: "ast_meissen",
      title: "Meissen Blue Onion · 12-place service",
      maker: "Meissen",
      category: "cat_porcelain",
      vertical: "porcelain",
      mode: "structured-set",
      tracking: { childCount: 86, set: "12-place" },
      location: { propId: "wardian", roomId: "r4", sub: "Display cabinet · upper", custody: "with-owner" },
      condition: "Excellent",
      status: "Owned",
      acquired: "Inherited 2017",
      acquisitionCost: null, currency: "GBP",
      value: { current: 22000, source: "Bonhams appraisal · 2024", insured: 28000 },
      tags: ["heirloom", "fragile"],
      collections: ["col_wardian_main"],
      photo: { fill: "linear-gradient(140deg,#E3EBF5 0%,#B0C8E0 60%,#7C9EC4 100%)", icon: "Glass" },
      docs: 4,
      timelineCount: 6,
      attrs: { Maker: "Meissen", Pattern: "Blue Onion", Country: "Germany", "Production period": "c. 1955–1960", "Hand painted": "Yes" },
      completeness: 0.81,
    },
    // ────── Furniture ──────
    {
      id: "ast_eames",
      title: "Eames Lounge Chair & Ottoman",
      maker: "Herman Miller",
      category: "cat_furniture",
      vertical: "furniture",
      mode: "structured-set",
      tracking: { childCount: 2 },
      location: { propId: "wardian", roomId: "r3", sub: "Reading nook", custody: "with-owner" },
      condition: "Excellent",
      status: "Owned",
      acquired: "2022-01-08",
      acquisitionCost: 7400, currency: "GBP",
      value: { current: 7000, source: "Replacement cost", insured: 8000 },
      tags: ["statement"],
      collections: ["col_insurable", "col_wardian_main"],
      photo: { fill: "linear-gradient(140deg,#1E1A14 0%,#3D3024 60%,#5C4836 100%)", icon: "Chair" },
      docs: 2,
      timelineCount: 4,
      attrs: { Maker: "Herman Miller", Model: "Eames Lounge 670/671", Material: "Rosewood veneer · black leather", Finish: "Original", Dimensions: "84 × 84 × 80 cm" },
      completeness: 0.88,
    },
    // ────── Clothing ──────
    {
      id: "ast_brioni",
      title: "Brioni Vanquish II navy suit",
      maker: "Brioni",
      category: "cat_suits",
      vertical: "clothing",
      mode: "unique",
      location: { propId: "wardian", roomId: "r1", sub: "Walk-in · suits rail · 4", custody: "with-owner" },
      condition: "Excellent",
      status: "Owned",
      acquired: "2024-02-14",
      acquisitionCost: 6800, currency: "GBP",
      value: { current: 5200, source: "Depreciated", insured: null },
      tags: ["formal"],
      collections: ["col_seasonal", "col_wardian_main"],
      photo: { fill: "linear-gradient(140deg,#0A1A33 0%,#1B2E52 60%,#2A4275 100%)", icon: "Shirt" },
      docs: 1,
      timelineCount: 6,
      attrs: { Brand: "Brioni", Size: "50R", "Material composition": "Vanquish II super-180s wool", Colour: "Navy", Season: "All-season", "Wear count": "14", "Dry cleaning history": "2× in 2025", Alterations: "Trouser hem · Henry Poole · 2024" },
      completeness: 0.92,
    },
    {
      id: "ast_loro",
      title: "Loro Piana cashmere overcoat",
      maker: "Loro Piana",
      category: "cat_outerwear",
      vertical: "clothing",
      mode: "unique",
      location: { propId: "wardian", roomId: "r1", sub: "Walk-in · coats rail · 2", custody: "with-owner" },
      condition: "Excellent",
      status: "Owned",
      acquired: "2023-11-04",
      acquisitionCost: 4200, currency: "GBP",
      value: { current: 3400, source: "Depreciated", insured: null },
      tags: ["winter"],
      collections: ["col_seasonal", "col_wardian_main"],
      photo: { fill: "linear-gradient(140deg,#2A1F18 0%,#4A3422 60%,#705032 100%)", icon: "Shirt" },
      docs: 1,
      timelineCount: 3,
      attrs: { Brand: "Loro Piana", Size: "M", "Material composition": "100% baby cashmere", Colour: "Vicuña", Season: "Winter", "Wear count": "32", "Dry cleaning history": "1× in Mar 2025" },
      completeness: 0.86,
    },
    {
      id: "ast_alden",
      title: "Alden 990 longwing · cordovan",
      maker: "Alden Shoe Co.",
      category: "cat_shoes",
      vertical: "clothing",
      mode: "unique",
      location: { propId: "wardian", roomId: "r1", sub: "Walk-in · shoe rack · 3", custody: "with-owner" },
      condition: "Good",
      status: "Owned",
      acquired: "2020-10-22",
      acquisitionCost: 720, currency: "GBP",
      value: { current: 450, source: "Depreciated", insured: null },
      tags: ["business"],
      collections: ["col_wardian_main"],
      photo: { fill: "linear-gradient(140deg,#3E1B14 0%,#6B2D1F 60%,#94402D 100%)", icon: "Shirt" },
      docs: 1,
      timelineCount: 5,
      attrs: { Brand: "Alden", Size: "9.5D", "Material composition": "Shell cordovan / leather sole", Colour: "Color 8", "Wear count": "120+", "Sole replacement history": "Re-soled 2024 · B. Nelson NYC" },
      completeness: 0.82,
    },
    // ────── Art ──────
    {
      id: "ast_picasso",
      title: "Picasso · 'La Colombe' lithograph (signed)",
      maker: "Pablo Picasso",
      category: "cat_art",
      vertical: "art",
      mode: "unique",
      location: { propId: "wardian", roomId: "r3", sub: "Wall · north", custody: "with-owner" },
      condition: "Excellent",
      status: "Owned",
      acquired: "Inherited 2017",
      acquisitionCost: null, currency: "GBP",
      value: { current: 92000, source: "Christie's appraisal · Sep 2024", insured: 110000 },
      tags: ["heirloom", "investment"],
      collections: ["col_insurable", "col_wardian_main", "col_estate"],
      photo: { fill: "linear-gradient(140deg,#F0E8D8 0%,#D9C49C 60%,#A38255 100%)", icon: "Art" },
      docs: 6,
      timelineCount: 8,
      attrs: { Artist: "Pablo Picasso", Title: "La Colombe", Year: "1949", Medium: "Lithograph on Arches", "Edition": "44/200", Signed: "Yes — pencil signed lower right", Provenance: "Galerie Louise Leiris → estate" },
      completeness: 0.96,
    },
  ],
  // Stub: more assets in summary form (we only show 12 fully)
  assetTotal: 165,
  totalValue: 274_800,
  recentEvents: [
    {
      id: "ev_e1", assetId: "ast_jlc", at: "2026-05-18", type: "service-sent",
      title: "Sent for service — JLC London",
      detail: "Full service quote £820. Estimated return: 28 May.",
      cost: null, party: "JLC Service Centre",
    },
    {
      id: "ev_e2", assetId: "ast_picasso", at: "2026-05-10", type: "valuation",
      title: "Valuation snapshot · Christie's",
      detail: "Insured value increased from £95,000 to £110,000.",
      cost: null, deltaValue: 15000,
    },
    {
      id: "ev_e3", assetId: "ast_brioni", at: "2026-05-04", type: "cleaning",
      title: "Dry cleaned — Henry Poole",
      cost: 38, currency: "GBP", party: "Henry Poole & Co.",
    },
    {
      id: "ev_e4", assetId: "ast_riedel", at: "2026-04-22", type: "damage",
      title: "Lost one glass — kitchen breakage",
      detail: "Set reduced from 9 → 8.",
    },
    {
      id: "ev_e5", assetId: "ast_les_paul", at: "2026-03-14", type: "setup",
      title: "Pro setup — Wunjos",
      cost: 145, currency: "GBP", party: "Wunjo Guitars",
    },
  ],
  // Asset attributes index used for completeness scoring + filters
  totalCompleteness: 0.84,
  dataQuality: {
    missingPhoto: 9,
    missingCategory: 0,
    missingLocation: 3,
    missingProof: 14,
    expensiveMissingProof: 2,
    suspectedDuplicates: 1,
  },
  // Reconciliation queue (bank txn ↔ receipt)
  reconciliation: [
    { id: "rec1", date: "2026-05-19", merchant: "John Lewis", amount: 749.99, currency: "GBP", account: "Coutts · 0418", state: "matched", receiptId: "rcp_jl_001", confidence: 0.99 },
    { id: "rec2", date: "2026-05-18", merchant: "Henry Poole & Co", amount: 38.00, currency: "GBP", account: "Amex · 1003", state: "unmatched", note: "Awaiting receipt upload" },
    { id: "rec3", date: "2026-05-14", merchant: "Square Mile Coffee", amount: 84.00, currency: "GBP", account: "Coutts · 0418", state: "suggested", suggestedReceiptId: "rcp_sm_009", confidence: 0.82 },
    { id: "rec4", date: "2026-05-11", merchant: "Christie's", amount: 320.00, currency: "GBP", account: "Coutts · 9871", state: "matched", receiptId: "rcp_chr_002", confidence: 1.0 },
    { id: "rec5", date: "2026-05-09", merchant: "Selfridges", amount: 1240.00, currency: "GBP", account: "Amex · 1003", state: "split", note: "Split across 3 line items" },
    { id: "rec6", date: "2026-05-08", merchant: "Wunjo Guitars", amount: 145.00, currency: "GBP", account: "Coutts · 0418", state: "matched", receiptId: "rcp_wun_001", confidence: 0.95 },
    { id: "rec7", date: "2026-05-05", merchant: "DPD", amount: 12.40, currency: "GBP", account: "Amex · 1003", state: "ignored", note: "Sub-£20 marker" },
  ],
  // Receipts with line items (a few)
  receipts: [
    {
      id: "rcp_jl_001",
      merchant: "John Lewis",
      total: 749.99, currency: "GBP",
      date: "2026-05-19",
      lines: [
        { name: "Dyson V15 Detect Absolute", qty: 1, price: 699.99, assetId: null, suggestion: "Create asset" },
        { name: "Extended care (3yr)", qty: 1, price: 50.00, assetId: null },
      ],
      parseRuns: 1, version: 1,
    },
    {
      id: "rcp_selfridges_05",
      merchant: "Selfridges",
      total: 1240.00, currency: "GBP",
      date: "2026-05-09",
      lines: [
        { name: "Drake's silk tie · navy paisley", qty: 1, price: 195.00, assetId: null, suggestion: "Create asset" },
        { name: "Drake's silk tie · burgundy stripe", qty: 1, price: 195.00, assetId: null, suggestion: "Create asset" },
        { name: "Drake's pocket squares (×3)", qty: 3, price: 95.00, assetId: null, suggestion: "Group + create" },
        { name: "Smythson notebook · panama black", qty: 1, price: 565.00, assetId: null, suggestion: "Create asset" },
      ],
      parseRuns: 2, version: 2,
    },
  ],
  // Backup state
  backup: {
    lastFull: "2026-05-22T03:00:00Z",
    lastFullSizeMB: 1843,
    lastFullStatus: "Success",
    nextScheduled: "2026-05-23T03:00:00Z",
    autoFrequency: "Daily",
    encryption: { enabled: true, algorithm: "age" },
    annualSnapshots: [
      { year: 2025, at: "2026-01-01T00:00:00Z", sizeMB: 1620, integrity: "Verified", immutable: true },
      { year: 2024, at: "2025-01-01T00:00:00Z", sizeMB: 1410, integrity: "Verified", immutable: true },
    ],
    entityCounts: { assets: 165, documents: 842, "bank_transactions": 9120, "receipts": 218, "ledger_postings": 41320 },
  },
  documents: [
    { id: "doc1", name: "Rolex Submariner — purchase invoice.pdf", category: "Receipt", attachedTo: { type: "asset", label: "Rolex Submariner Date" }, size: "412 KB", uploaded: "2019-06-12", parseRuns: 1, lineItems: 1, immutable: true, source: "manual", access: "Principal" },
    { id: "doc2", name: "AP Royal Oak — warranty card.pdf", category: "Warranty", attachedTo: { type: "asset", label: "AP Royal Oak" }, size: "1.2 MB", uploaded: "2022-03-30", immutable: true, source: "manual", access: "Principal" },
    { id: "doc3", name: "Picasso lithograph — Christie's appraisal.pdf", category: "Appraisal", attachedTo: { type: "asset", label: "Picasso 'La Colombe'" }, size: "2.4 MB", uploaded: "2024-09-12", immutable: true, source: "manual", access: "Principal" },
    { id: "doc4", name: "John Lewis · Dyson V15 receipt.pdf", category: "Receipt", attachedTo: { type: "txn", label: "Coutts · 19 May 2026" }, size: "240 KB", uploaded: "2026-05-19", parseRuns: 1, lineItems: 2, immutable: true, source: "agent", access: "Operational" },
    { id: "doc5", name: "Brioni — Henry Poole alterations invoice.pdf", category: "Service", attachedTo: { type: "asset", label: "Brioni navy suit" }, size: "180 KB", uploaded: "2024-02-22", immutable: true, source: "manual", access: "Operational" },
    { id: "doc6", name: "Hiscox · contents schedule 2026.pdf", category: "Insurance", attachedTo: { type: "property", label: "Wardian" }, size: "3.1 MB", uploaded: "2026-01-22", immutable: true, source: "manual", access: "Principal" },
    { id: "doc7", name: "Meissen tea set — Bonhams appraisal.pdf", category: "Appraisal", attachedTo: { type: "asset", label: "Meissen Blue Onion" }, size: "1.8 MB", uploaded: "2024-04-04", immutable: true, source: "manual", access: "Principal" },
    { id: "doc8", name: "Coutts statement · April 2026.pdf", category: "Statement", attachedTo: { type: "account", label: "Coutts · 0418" }, size: "320 KB", uploaded: "2026-05-02", immutable: true, source: "agent", access: "Principal" },
  ],
};

// Build an asset-by-id index for fast lookup
window.INVENTORY.assetById = {};
window.INVENTORY.assets.forEach(a => { window.INVENTORY.assetById[a.id] = a; });

// Timeline events per asset (synthesised, not stored separately)
window.INVENTORY.timelines = {
  ast_rolex: [
    { at: "2026-05-12", type: "valuation", title: "Valuation snapshot", detail: "Market £11,200 · source Bob's Watches", deltaValue: 200 },
    { at: "2025-08-04", type: "service", title: "Full service complete", detail: "5-yr service · returned in original packaging", cost: 620, party: "Rolex Service Centre · London" },
    { at: "2025-07-12", type: "service-sent", title: "Sent for service", party: "Rolex Service Centre · London" },
    { at: "2023-11-20", type: "appraisal", title: "Appraised", detail: "Insurance valuation refresh", deltaValue: 1500 },
    { at: "2021-04-04", type: "moved", title: "Moved to Wardian safe", detail: "From dressing-table drawer" },
    { at: "2019-06-12", type: "acquired", title: "Acquired from Watches of Switzerland", cost: 8950, currency: "GBP", party: "Watches of Switzerland · Brompton Rd" },
    { at: "2019-06-12", type: "document", title: "Receipt + guarantee filed", detail: "doc_rolex_purchase.pdf, doc_rolex_warranty.pdf" },
  ],
  ast_ap: [
    { at: "2026-04-12", type: "valuation", title: "Market valuation refresh", detail: "Source Watchfinder · April 2026", deltaValue: 4000 },
    { at: "2023-09-22", type: "appraisal", title: "Insurance appraisal", deltaValue: 6000 },
    { at: "2022-04-02", type: "moved", title: "Moved to Wardian safe" },
    { at: "2022-03-30", type: "acquired", title: "Acquired from Audemars Piguet boutique", cost: 36500, currency: "GBP", party: "Audemars Piguet · Bond Street" },
  ],
  ast_jlc: [
    { at: "2026-05-18", type: "service-sent", title: "Sent for service", detail: "Quote £820. Est. return 28 May", party: "JLC Service Centre · London" },
    { at: "2026-05-18", type: "custody", title: "Custody changed → with vendor" },
    { at: "2024-05-22", type: "service", title: "Full service complete", cost: 740, party: "JLC Service Centre · London" },
    { at: "2024-03-04", type: "appraisal", title: "Insurance appraisal", deltaValue: 500 },
    { at: "2021-09-04", type: "service", title: "Crown gasket replacement", cost: 180, party: "JLC Service · Geneva" },
    { at: "2020-01-12", type: "moved", title: "Moved to Wardian safe" },
    { at: "2015-09-04", type: "acquired", title: "Acquired", cost: 6200, currency: "GBP", party: "Jaeger-LeCoultre boutique · Old Bond St" },
  ],
  ast_les_paul: [
    { at: "2026-03-14", type: "service", title: "Pro setup — Wunjos", cost: 145, party: "Wunjo Guitars" },
    { at: "2024-08-11", type: "moved", title: "Moved to Wardian studio rack" },
    { at: "2022-06-02", type: "service", title: "New strings · fret polish", cost: 65, party: "Wunjo Guitars" },
    { at: "2019-03-04", type: "valuation", title: "Market valuation", deltaValue: 800 },
    { at: "2018-11-20", type: "acquired", title: "Acquired", cost: 5400, currency: "GBP", party: "Gibson Garage · London" },
  ],
  ast_picasso: [
    { at: "2026-05-10", type: "valuation", title: "Valuation refresh", detail: "Insured value £95,000 → £110,000", deltaValue: 15000 },
    { at: "2024-09-12", type: "appraisal", title: "Christie's appraisal", cost: 320, party: "Christie's · Specialist department" },
    { at: "2024-09-04", type: "document", title: "Appraisal scope confirmed" },
    { at: "2023-04-22", type: "moved", title: "Re-hung — Wardian living room north wall" },
    { at: "2017-11-15", type: "acquired", title: "Inherited", detail: "From the estate of A. Kanzen — see estate documents" },
  ],
  ast_brioni: [
    { at: "2026-05-04", type: "cleaning", title: "Dry cleaned", cost: 38, currency: "GBP", party: "Henry Poole & Co." },
    { at: "2025-12-12", type: "cleaning", title: "Dry cleaned", cost: 38, currency: "GBP", party: "Henry Poole & Co." },
    { at: "2024-09-04", type: "wear", title: "Worn — Royal Ascot" },
    { at: "2024-04-22", type: "wear", title: "Worn — Sotheby's gala" },
    { at: "2024-02-22", type: "service", title: "Trouser hem · Henry Poole alteration", cost: 95, party: "Henry Poole & Co." },
    { at: "2024-02-14", type: "acquired", title: "Acquired", cost: 6800, currency: "GBP", party: "Brioni · Bond Street" },
  ],
  ast_riedel: [
    { at: "2026-04-22", type: "damage", title: "Glass lost · kitchen breakage", detail: "Quantity 9 → 8" },
    { at: "2025-06-04", type: "damage", title: "Glass lost · dinner party", detail: "Quantity 10 → 9" },
    { at: "2023-08-04", type: "damage", title: "Glass lost · moving · 2 broken", detail: "Quantity 12 → 10" },
    { at: "2021-12-18", type: "acquired", title: "Acquired", cost: 720, currency: "GBP", party: "Riedel UK" },
  ],
  ast_meissen: [
    { at: "2024-04-04", type: "appraisal", title: "Bonhams appraisal", cost: 480, party: "Bonhams · Specialist Asian & European Ceramics" },
    { at: "2023-11-22", type: "cleaning", title: "Professional clean · display cabinet", cost: 240, party: "ArtCare London" },
    { at: "2022-06-30", type: "moved", title: "Moved to Wardian display cabinet" },
    { at: "2017-11-15", type: "acquired", title: "Inherited", detail: "From the estate of A. Kanzen" },
  ],
  ast_d28: [
    { at: "2024-11-12", type: "service", title: "Re-fret + setup", cost: 380, party: "Wunjo Guitars" },
    { at: "2022-04-30", type: "moved", title: "Moved to Wardian studio rack" },
    { at: "2020-08-04", type: "acquired", title: "Acquired", cost: 7800, currency: "GBP", party: "Hank's · London" },
  ],
  ast_eames: [
    { at: "2024-06-11", type: "service", title: "Leather conditioning treatment", cost: 180, party: "Vitra Care UK" },
    { at: "2022-01-15", type: "moved", title: "Delivered + assembled — Wardian living room" },
    { at: "2022-01-08", type: "acquired", title: "Acquired", cost: 7400, currency: "GBP", party: "Aram · Drury Lane" },
  ],
  ast_loro: [
    { at: "2025-03-12", type: "cleaning", title: "Dry cleaned", cost: 42, currency: "GBP", party: "Henry Poole & Co." },
    { at: "2024-12-04", type: "wear", title: "Worn — winter season" },
    { at: "2023-11-04", type: "acquired", title: "Acquired", cost: 4200, currency: "GBP", party: "Loro Piana · Sloane Street" },
  ],
  ast_alden: [
    { at: "2024-08-22", type: "service", title: "Re-soled", cost: 240, party: "B. Nelson Shoes · NYC" },
    { at: "2024-02-04", type: "service", title: "Cordovan conditioning", cost: 60, party: "Saphir · in-house" },
    { at: "2022-04-12", type: "wear", title: "Wear count crossed 100" },
    { at: "2020-10-22", type: "acquired", title: "Acquired", cost: 720, currency: "GBP", party: "Leffot · NYC" },
  ],
};

// Format helpers shared with rest of app
window.fmtMoneyShort = (amount, currency) => {
  if (amount == null) return "—";
  try {
    const sym = new Intl.NumberFormat("en-GB", { style: "currency", currency, maximumFractionDigits: 0 }).format(amount);
    return sym;
  } catch { return `${currency} ${amount}`; }
};
