-- Seed the global brand catalogue from curated research (specs/03-brand-catalogue.md). Seeded as
-- 'verified'; seed usage_count gives marquee brands a head start in ranking. Community entries are
-- added by users at runtime via POST /api/brands. Idempotent on (category, normalized).
insert into brands (name, normalized, category, status, usage_count) values
  ('Rolex', 'rolex', 'watches', 'verified', 530),
  ('Patek Philippe', 'patek philippe', 'watches', 'verified', 520),
  ('Audemars Piguet', 'audemars piguet', 'watches', 'verified', 510),
  ('Vacheron Constantin', 'vacheron constantin', 'watches', 'verified', 500),
  ('A. Lange & Söhne', 'a. lange & söhne', 'watches', 'verified', 490),
  ('Jaeger-LeCoultre', 'jaeger-lecoultre', 'watches', 'verified', 480),
  ('Omega', 'omega', 'watches', 'verified', 470),
  ('Cartier', 'cartier', 'watches', 'verified', 460),
  ('Breguet', 'breguet', 'watches', 'verified', 450),
  ('Blancpain', 'blancpain', 'watches', 'verified', 440),
  ('IWC Schaffhausen', 'iwc schaffhausen', 'watches', 'verified', 430),
  ('Panerai', 'panerai', 'watches', 'verified', 420),
  ('Hublot', 'hublot', 'watches', 'verified', 410),
  ('Richard Mille', 'richard mille', 'watches', 'verified', 400),
  ('Tudor', 'tudor', 'watches', 'verified', 390),
  ('Grand Seiko', 'grand seiko', 'watches', 'verified', 380),
  ('Zenith', 'zenith', 'watches', 'verified', 370),
  ('Breitling', 'breitling', 'watches', 'verified', 360),
  ('TAG Heuer', 'tag heuer', 'watches', 'verified', 350),
  ('Chopard', 'chopard', 'watches', 'verified', 340),
  ('Piaget', 'piaget', 'watches', 'verified', 330),
  ('Girard-Perregaux', 'girard-perregaux', 'watches', 'verified', 320),
  ('Ulysse Nardin', 'ulysse nardin', 'watches', 'verified', 310),
  ('Glashütte Original', 'glashütte original', 'watches', 'verified', 300),
  ('H. Moser & Cie.', 'h. moser & cie.', 'watches', 'verified', 290),
  ('F.P. Journe', 'f.p. journe', 'watches', 'verified', 280),
  ('Parmigiani Fleurier', 'parmigiani fleurier', 'watches', 'verified', 270),
  ('Bovet', 'bovet', 'watches', 'verified', 260),
  ('MB&F', 'mb&f', 'watches', 'verified', 250),
  ('Roger Dubuis', 'roger dubuis', 'watches', 'verified', 240),
  ('Franck Muller', 'franck muller', 'watches', 'verified', 230),
  ('Bell & Ross', 'bell & ross', 'watches', 'verified', 220),
  ('Longines', 'longines', 'watches', 'verified', 210),
  ('Tissot', 'tissot', 'watches', 'verified', 200),
  ('Seiko', 'seiko', 'watches', 'verified', 190),
  ('Citizen', 'citizen', 'watches', 'verified', 180),
  ('NOMOS Glashütte', 'nomos glashütte', 'watches', 'verified', 170),
  ('Oris', 'oris', 'watches', 'verified', 160),
  ('Montblanc', 'montblanc', 'watches', 'verified', 150),
  ('Frederique Constant', 'frederique constant', 'watches', 'verified', 140),
  ('Raymond Weil', 'raymond weil', 'watches', 'verified', 130),
  ('Baume & Mercier', 'baume & mercier', 'watches', 'verified', 120),
  ('Maurice Lacroix', 'maurice lacroix', 'watches', 'verified', 110),
  ('Rado', 'rado', 'watches', 'verified', 100),
  ('Hamilton', 'hamilton', 'watches', 'verified', 90),
  ('Junghans', 'junghans', 'watches', 'verified', 80),
  ('Sinn', 'sinn', 'watches', 'verified', 70),
  ('Bremont', 'bremont', 'watches', 'verified', 60),
  ('Christopher Ward', 'christopher ward', 'watches', 'verified', 50),
  ('Laurent Ferrier', 'laurent ferrier', 'watches', 'verified', 40),
  ('De Bethune', 'de bethune', 'watches', 'verified', 30),
  ('Czapek', 'czapek', 'watches', 'verified', 20),
  ('Ressence', 'ressence', 'watches', 'verified', 10),
  ('Cartier', 'cartier', 'jewellery', 'verified', 310),
  ('Van Cleef & Arpels', 'van cleef & arpels', 'jewellery', 'verified', 300),
  ('Tiffany & Co.', 'tiffany & co.', 'jewellery', 'verified', 290),
  ('Bulgari', 'bulgari', 'jewellery', 'verified', 280),
  ('Harry Winston', 'harry winston', 'jewellery', 'verified', 270),
  ('Graff', 'graff', 'jewellery', 'verified', 260),
  ('Chopard', 'chopard', 'jewellery', 'verified', 250),
  ('Boucheron', 'boucheron', 'jewellery', 'verified', 240),
  ('Piaget', 'piaget', 'jewellery', 'verified', 230),
  ('Buccellati', 'buccellati', 'jewellery', 'verified', 220),
  ('Chaumet', 'chaumet', 'jewellery', 'verified', 210),
  ('Mikimoto', 'mikimoto', 'jewellery', 'verified', 200),
  ('David Yurman', 'david yurman', 'jewellery', 'verified', 190),
  ('Pomellato', 'pomellato', 'jewellery', 'verified', 180),
  ('Messika', 'messika', 'jewellery', 'verified', 170),
  ('De Beers', 'de beers', 'jewellery', 'verified', 160),
  ('Fred', 'fred', 'jewellery', 'verified', 150),
  ('Damiani', 'damiani', 'jewellery', 'verified', 140),
  ('Mauboussin', 'mauboussin', 'jewellery', 'verified', 130),
  ('Mellerio', 'mellerio', 'jewellery', 'verified', 120),
  ('Verdura', 'verdura', 'jewellery', 'verified', 110),
  ('JAR', 'jar', 'jewellery', 'verified', 100),
  ('Ilias Lalaounis', 'ilias lalaounis', 'jewellery', 'verified', 90),
  ('Marina B', 'marina b', 'jewellery', 'verified', 80),
  ('Repossi', 'repossi', 'jewellery', 'verified', 70),
  ('Stephen Webster', 'stephen webster', 'jewellery', 'verified', 60),
  ('Georg Jensen', 'georg jensen', 'jewellery', 'verified', 50),
  ('Tasaki', 'tasaki', 'jewellery', 'verified', 40),
  ('Qeelin', 'qeelin', 'jewellery', 'verified', 30),
  ('Anita Ko', 'anita ko', 'jewellery', 'verified', 20),
  ('Pippa Small', 'pippa small', 'jewellery', 'verified', 10),
  ('Mercedes-Benz', 'mercedes-benz', 'vehicles', 'verified', 510),
  ('BMW', 'bmw', 'vehicles', 'verified', 500),
  ('Audi', 'audi', 'vehicles', 'verified', 490),
  ('Porsche', 'porsche', 'vehicles', 'verified', 480),
  ('Ferrari', 'ferrari', 'vehicles', 'verified', 470),
  ('Lamborghini', 'lamborghini', 'vehicles', 'verified', 460),
  ('Bentley', 'bentley', 'vehicles', 'verified', 450),
  ('Rolls-Royce', 'rolls-royce', 'vehicles', 'verified', 440),
  ('Aston Martin', 'aston martin', 'vehicles', 'verified', 430),
  ('McLaren', 'mclaren', 'vehicles', 'verified', 420),
  ('Maserati', 'maserati', 'vehicles', 'verified', 410),
  ('Bugatti', 'bugatti', 'vehicles', 'verified', 400),
  ('Pagani', 'pagani', 'vehicles', 'verified', 390),
  ('Koenigsegg', 'koenigsegg', 'vehicles', 'verified', 380),
  ('Jaguar', 'jaguar', 'vehicles', 'verified', 370),
  ('Land Rover', 'land rover', 'vehicles', 'verified', 360),
  ('Range Rover', 'range rover', 'vehicles', 'verified', 350),
  ('Tesla', 'tesla', 'vehicles', 'verified', 340),
  ('Lexus', 'lexus', 'vehicles', 'verified', 330),
  ('Genesis', 'genesis', 'vehicles', 'verified', 320),
  ('Volvo', 'volvo', 'vehicles', 'verified', 310),
  ('Polestar', 'polestar', 'vehicles', 'verified', 300),
  ('Volkswagen', 'volkswagen', 'vehicles', 'verified', 290),
  ('Toyota', 'toyota', 'vehicles', 'verified', 280),
  ('Honda', 'honda', 'vehicles', 'verified', 270),
  ('Nissan', 'nissan', 'vehicles', 'verified', 260),
  ('Mazda', 'mazda', 'vehicles', 'verified', 250),
  ('Subaru', 'subaru', 'vehicles', 'verified', 240),
  ('Ford', 'ford', 'vehicles', 'verified', 230),
  ('Chevrolet', 'chevrolet', 'vehicles', 'verified', 220),
  ('Cadillac', 'cadillac', 'vehicles', 'verified', 210),
  ('Lincoln', 'lincoln', 'vehicles', 'verified', 200),
  ('Lotus', 'lotus', 'vehicles', 'verified', 190),
  ('Alpine', 'alpine', 'vehicles', 'verified', 180),
  ('Alfa Romeo', 'alfa romeo', 'vehicles', 'verified', 170),
  ('Fiat', 'fiat', 'vehicles', 'verified', 160),
  ('MINI', 'mini', 'vehicles', 'verified', 150),
  ('Peugeot', 'peugeot', 'vehicles', 'verified', 140),
  ('Renault', 'renault', 'vehicles', 'verified', 130),
  ('Citroën', 'citroën', 'vehicles', 'verified', 120),
  ('DS Automobiles', 'ds automobiles', 'vehicles', 'verified', 110),
  ('Hyundai', 'hyundai', 'vehicles', 'verified', 100),
  ('Kia', 'kia', 'vehicles', 'verified', 90),
  ('Rivian', 'rivian', 'vehicles', 'verified', 80),
  ('Lucid', 'lucid', 'vehicles', 'verified', 70),
  ('Morgan', 'morgan', 'vehicles', 'verified', 60),
  ('Ducati', 'ducati', 'vehicles', 'verified', 50),
  ('Harley-Davidson', 'harley-davidson', 'vehicles', 'verified', 40),
  ('Triumph', 'triumph', 'vehicles', 'verified', 30),
  ('BMW Motorrad', 'bmw motorrad', 'vehicles', 'verified', 20),
  ('Royal Enfield', 'royal enfield', 'vehicles', 'verified', 10),
  ('Herman Miller', 'herman miller', 'furniture', 'verified', 380),
  ('Knoll', 'knoll', 'furniture', 'verified', 370),
  ('Cassina', 'cassina', 'furniture', 'verified', 360),
  ('B&B Italia', 'b&b italia', 'furniture', 'verified', 350),
  ('Vitra', 'vitra', 'furniture', 'verified', 340),
  ('Minotti', 'minotti', 'furniture', 'verified', 330),
  ('Poliform', 'poliform', 'furniture', 'verified', 320),
  ('Roche Bobois', 'roche bobois', 'furniture', 'verified', 310),
  ('Ligne Roset', 'ligne roset', 'furniture', 'verified', 300),
  ('Fritz Hansen', 'fritz hansen', 'furniture', 'verified', 290),
  ('Carl Hansen & Søn', 'carl hansen & søn', 'furniture', 'verified', 280),
  ('Molteni&C', 'molteni&c', 'furniture', 'verified', 270),
  ('Flexform', 'flexform', 'furniture', 'verified', 260),
  ('Poltrona Frau', 'poltrona frau', 'furniture', 'verified', 250),
  ('Edra', 'edra', 'furniture', 'verified', 240),
  ('Moooi', 'moooi', 'furniture', 'verified', 230),
  ('Kartell', 'kartell', 'furniture', 'verified', 220),
  ('USM Haller', 'usm haller', 'furniture', 'verified', 210),
  ('Thonet', 'thonet', 'furniture', 'verified', 200),
  ('Ercol', 'ercol', 'furniture', 'verified', 190),
  ('G Plan', 'g plan', 'furniture', 'verified', 180),
  ('de Sede', 'de sede', 'furniture', 'verified', 170),
  ('Walter Knoll', 'walter knoll', 'furniture', 'verified', 160),
  ('Cappellini', 'cappellini', 'furniture', 'verified', 150),
  ('Artek', 'artek', 'furniture', 'verified', 140),
  ('Gubi', 'gubi', 'furniture', 'verified', 130),
  ('HAY', 'hay', 'furniture', 'verified', 120),
  ('&Tradition', '&tradition', 'furniture', 'verified', 110),
  ('Muuto', 'muuto', 'furniture', 'verified', 100),
  ('Holly Hunt', 'holly hunt', 'furniture', 'verified', 90),
  ('Baker', 'baker', 'furniture', 'verified', 80),
  ('Henredon', 'henredon', 'furniture', 'verified', 70),
  ('Ralph Lauren Home', 'ralph lauren home', 'furniture', 'verified', 60),
  ('RH (Restoration Hardware)', 'rh (restoration hardware)', 'furniture', 'verified', 50),
  ('Vitsœ', 'vitsœ', 'furniture', 'verified', 40),
  ('Tom Dixon', 'tom dixon', 'furniture', 'verified', 30),
  ('De La Espada', 'de la espada', 'furniture', 'verified', 20),
  ('Maker&Son', 'maker&son', 'furniture', 'verified', 10),
  ('Hermès', 'hermès', 'clothing', 'verified', 370),
  ('Chanel', 'chanel', 'clothing', 'verified', 360),
  ('Louis Vuitton', 'louis vuitton', 'clothing', 'verified', 350),
  ('Dior', 'dior', 'clothing', 'verified', 340),
  ('Gucci', 'gucci', 'clothing', 'verified', 330),
  ('Prada', 'prada', 'clothing', 'verified', 320),
  ('Loro Piana', 'loro piana', 'clothing', 'verified', 310),
  ('Brunello Cucinelli', 'brunello cucinelli', 'clothing', 'verified', 300),
  ('Ermenegildo Zegna', 'ermenegildo zegna', 'clothing', 'verified', 290),
  ('Tom Ford', 'tom ford', 'clothing', 'verified', 280),
  ('Saint Laurent', 'saint laurent', 'clothing', 'verified', 270),
  ('Bottega Veneta', 'bottega veneta', 'clothing', 'verified', 260),
  ('Burberry', 'burberry', 'clothing', 'verified', 250),
  ('Brioni', 'brioni', 'clothing', 'verified', 240),
  ('Kiton', 'kiton', 'clothing', 'verified', 230),
  ('Loewe', 'loewe', 'clothing', 'verified', 220),
  ('Celine', 'celine', 'clothing', 'verified', 210),
  ('Givenchy', 'givenchy', 'clothing', 'verified', 200),
  ('Balenciaga', 'balenciaga', 'clothing', 'verified', 190),
  ('Valentino', 'valentino', 'clothing', 'verified', 180),
  ('Versace', 'versace', 'clothing', 'verified', 170),
  ('Fendi', 'fendi', 'clothing', 'verified', 160),
  ('Moncler', 'moncler', 'clothing', 'verified', 150),
  ('Stone Island', 'stone island', 'clothing', 'verified', 140),
  ('Ralph Lauren', 'ralph lauren', 'clothing', 'verified', 130),
  ('Thom Browne', 'thom browne', 'clothing', 'verified', 120),
  ('Berluti', 'berluti', 'clothing', 'verified', 110),
  ('Canali', 'canali', 'clothing', 'verified', 100),
  ('Corneliani', 'corneliani', 'clothing', 'verified', 90),
  ('Isaia', 'isaia', 'clothing', 'verified', 80),
  ('Stefano Ricci', 'stefano ricci', 'clothing', 'verified', 70),
  ('Anderson & Sheppard', 'anderson & sheppard', 'clothing', 'verified', 60),
  ('Huntsman', 'huntsman', 'clothing', 'verified', 50),
  ('Drake''s', 'drake''s', 'clothing', 'verified', 40),
  ('Turnbull & Asser', 'turnbull & asser', 'clothing', 'verified', 30),
  ('Charvet', 'charvet', 'clothing', 'verified', 20),
  ('Cifonelli', 'cifonelli', 'clothing', 'verified', 10),
  ('Gibson', 'gibson', 'guitars', 'verified', 240),
  ('Fender', 'fender', 'guitars', 'verified', 230),
  ('Martin', 'martin', 'guitars', 'verified', 220),
  ('Taylor', 'taylor', 'guitars', 'verified', 210),
  ('PRS (Paul Reed Smith)', 'prs (paul reed smith)', 'guitars', 'verified', 200),
  ('Gretsch', 'gretsch', 'guitars', 'verified', 190),
  ('Rickenbacker', 'rickenbacker', 'guitars', 'verified', 180),
  ('Epiphone', 'epiphone', 'guitars', 'verified', 170),
  ('Ibanez', 'ibanez', 'guitars', 'verified', 160),
  ('Jackson', 'jackson', 'guitars', 'verified', 150),
  ('ESP', 'esp', 'guitars', 'verified', 140),
  ('Guild', 'guild', 'guitars', 'verified', 130),
  ('Yamaha', 'yamaha', 'guitars', 'verified', 120),
  ('Takamine', 'takamine', 'guitars', 'verified', 110),
  ('Collings', 'collings', 'guitars', 'verified', 100),
  ('Santa Cruz', 'santa cruz', 'guitars', 'verified', 90),
  ('Lowden', 'lowden', 'guitars', 'verified', 80),
  ('Suhr', 'suhr', 'guitars', 'verified', 70),
  ('Ernie Ball Music Man', 'ernie ball music man', 'guitars', 'verified', 60),
  ('Charvel', 'charvel', 'guitars', 'verified', 50),
  ('Danelectro', 'danelectro', 'guitars', 'verified', 40),
  ('National', 'national', 'guitars', 'verified', 30),
  ('Gibson Custom Shop', 'gibson custom shop', 'guitars', 'verified', 20),
  ('Fender Custom Shop', 'fender custom shop', 'guitars', 'verified', 10),
  ('Meissen', 'meissen', 'porcelain', 'verified', 200),
  ('Royal Copenhagen', 'royal copenhagen', 'porcelain', 'verified', 190),
  ('Wedgwood', 'wedgwood', 'porcelain', 'verified', 180),
  ('Herend', 'herend', 'porcelain', 'verified', 170),
  ('Limoges', 'limoges', 'porcelain', 'verified', 160),
  ('Sèvres', 'sèvres', 'porcelain', 'verified', 150),
  ('Royal Worcester', 'royal worcester', 'porcelain', 'verified', 140),
  ('Spode', 'spode', 'porcelain', 'verified', 130),
  ('Royal Doulton', 'royal doulton', 'porcelain', 'verified', 120),
  ('Lladró', 'lladró', 'porcelain', 'verified', 110),
  ('Nymphenburg', 'nymphenburg', 'porcelain', 'verified', 100),
  ('KPM Berlin', 'kpm berlin', 'porcelain', 'verified', 90),
  ('Bernardaud', 'bernardaud', 'porcelain', 'verified', 80),
  ('Haviland', 'haviland', 'porcelain', 'verified', 70),
  ('Rosenthal', 'rosenthal', 'porcelain', 'verified', 60),
  ('Augarten', 'augarten', 'porcelain', 'verified', 50),
  ('Royal Crown Derby', 'royal crown derby', 'porcelain', 'verified', 40),
  ('Minton', 'minton', 'porcelain', 'verified', 30),
  ('Villeroy & Boch', 'villeroy & boch', 'porcelain', 'verified', 20),
  ('Hutschenreuther', 'hutschenreuther', 'porcelain', 'verified', 10),
  ('Baccarat', 'baccarat', 'glassware', 'verified', 190),
  ('Lalique', 'lalique', 'glassware', 'verified', 180),
  ('Waterford', 'waterford', 'glassware', 'verified', 170),
  ('Riedel', 'riedel', 'glassware', 'verified', 160),
  ('Saint-Louis', 'saint-louis', 'glassware', 'verified', 150),
  ('Venini', 'venini', 'glassware', 'verified', 140),
  ('Daum', 'daum', 'glassware', 'verified', 130),
  ('Steuben', 'steuben', 'glassware', 'verified', 120),
  ('Orrefors', 'orrefors', 'glassware', 'verified', 110),
  ('Kosta Boda', 'kosta boda', 'glassware', 'verified', 100),
  ('Moser', 'moser', 'glassware', 'verified', 90),
  ('Swarovski', 'swarovski', 'glassware', 'verified', 80),
  ('Val Saint Lambert', 'val saint lambert', 'glassware', 'verified', 70),
  ('William Yeoward', 'william yeoward', 'glassware', 'verified', 60),
  ('Lobmeyr', 'lobmeyr', 'glassware', 'verified', 50),
  ('Iittala', 'iittala', 'glassware', 'verified', 40),
  ('Holmegaard', 'holmegaard', 'glassware', 'verified', 30),
  ('Nachtmann', 'nachtmann', 'glassware', 'verified', 20),
  ('Stuart Crystal', 'stuart crystal', 'glassware', 'verified', 10)
on conflict (category, normalized) do nothing;
