-- Furniture makers — seeded from the operator's curated list + a broad expansion
-- (specs/03-brand-catalogue.md). Idempotent: the ~38 furniture brands already in V2_69 are skipped
-- via ON CONFLICT. Low usage_count keeps the long tail searchable without outranking the marquee seed.
insert into brands (name, normalized, category, status, usage_count) values
  ('Clive Christian', 'clive christian', 'furniture', 'verified', 3),
  ('Shepel', 'shepel', 'furniture', 'verified', 3),
  ('Boca do Lobo', 'boca do lobo', 'furniture', 'verified', 3),
  ('Turri', 'turri', 'furniture', 'verified', 3),
  ('Giorgio Collection', 'giorgio collection', 'furniture', 'verified', 3),
  ('Visionnaire', 'visionnaire', 'furniture', 'verified', 3),
  ('Fendi Casa', 'fendi casa', 'furniture', 'verified', 3),
  ('Baxter', 'baxter', 'furniture', 'verified', 3),
  ('Giorgetti', 'giorgetti', 'furniture', 'verified', 3),
  ('Fratelli Boffi', 'fratelli boffi', 'furniture', 'verified', 3),
  ('Selva', 'selva', 'furniture', 'verified', 3),
  ('Smania', 'smania', 'furniture', 'verified', 3),
  ('Minotti', 'minotti', 'furniture', 'verified', 3),
  ('Poltrona Frau', 'poltrona frau', 'furniture', 'verified', 3),
  ('Flexform', 'flexform', 'furniture', 'verified', 3),
  ('Cassina', 'cassina', 'furniture', 'verified', 3),
  ('B&B Italia', 'b&b italia', 'furniture', 'verified', 3),
  ('Tom Faulkner', 'tom faulkner', 'furniture', 'verified', 3),
  ('Porada', 'porada', 'furniture', 'verified', 3),
  ('Roche Bobois', 'roche bobois', 'furniture', 'verified', 3),
  ('Fratto', 'fratto', 'furniture', 'verified', 3),
  ('Caracole', 'caracole', 'furniture', 'verified', 3),
  ('Eichholtz', 'eichholtz', 'furniture', 'verified', 3),
  ('Molteni&C', 'molteni&c', 'furniture', 'verified', 3),
  ('Poliform', 'poliform', 'furniture', 'verified', 3),
  ('Cappellini', 'cappellini', 'furniture', 'verified', 3),
  ('Edra', 'edra', 'furniture', 'verified', 3),
  ('Moroso', 'moroso', 'furniture', 'verified', 3),
  ('Arflex', 'arflex', 'furniture', 'verified', 3),
  ('Zanotta', 'zanotta', 'furniture', 'verified', 3),
  ('Driade', 'driade', 'furniture', 'verified', 3),
  ('Magis', 'magis', 'furniture', 'verified', 3),
  ('MDF Italia', 'mdf italia', 'furniture', 'verified', 3),
  ('Living Divani', 'living divani', 'furniture', 'verified', 3),
  ('Porro', 'porro', 'furniture', 'verified', 3),
  ('Lema', 'lema', 'furniture', 'verified', 3),
  ('Rimadesio', 'rimadesio', 'furniture', 'verified', 3),
  ('Natuzzi', 'natuzzi', 'furniture', 'verified', 3),
  ('Calligaris', 'calligaris', 'furniture', 'verified', 3),
  ('Promemoria', 'promemoria', 'furniture', 'verified', 3),
  ('Henge', 'henge', 'furniture', 'verified', 3),
  ('Flou', 'flou', 'furniture', 'verified', 3),
  ('Maxalto', 'maxalto', 'furniture', 'verified', 3),
  ('Pedrali', 'pedrali', 'furniture', 'verified', 3),
  ('Bonaldo', 'bonaldo', 'furniture', 'verified', 3),
  ('Cattelan Italia', 'cattelan italia', 'furniture', 'verified', 3),
  ('Riva 1920', 'riva 1920', 'furniture', 'verified', 3),
  ('Ceccotti Collezioni', 'ceccotti collezioni', 'furniture', 'verified', 3),
  ('Gallotti & Radice', 'gallotti & radice', 'furniture', 'verified', 3),
  ('FontanaArte', 'fontanaarte', 'furniture', 'verified', 3),
  ('Tacchini', 'tacchini', 'furniture', 'verified', 3),
  ('Saba Italia', 'saba italia', 'furniture', 'verified', 3),
  ('Desalto', 'desalto', 'furniture', 'verified', 3),
  ('Glas Italia', 'glas italia', 'furniture', 'verified', 3),
  ('Meritalia', 'meritalia', 'furniture', 'verified', 3),
  ('Kartell', 'kartell', 'furniture', 'verified', 3),
  ('Boffi', 'boffi', 'furniture', 'verified', 3),
  ('Rubelli', 'rubelli', 'furniture', 'verified', 3),
  ('Armani/Casa', 'armani/casa', 'furniture', 'verified', 3),
  ('Versace Home', 'versace home', 'furniture', 'verified', 3),
  ('Bentley Home', 'bentley home', 'furniture', 'verified', 3),
  ('Trussardi Casa', 'trussardi casa', 'furniture', 'verified', 3),
  ('Bugatti Home', 'bugatti home', 'furniture', 'verified', 3),
  ('Dolce & Gabbana Casa', 'dolce & gabbana casa', 'furniture', 'verified', 3),
  ('Etro Home', 'etro home', 'furniture', 'verified', 3),
  ('Ralph Lauren Home', 'ralph lauren home', 'furniture', 'verified', 3),
  ('Fritz Hansen', 'fritz hansen', 'furniture', 'verified', 3),
  ('Carl Hansen & Søn', 'carl hansen & søn', 'furniture', 'verified', 3),
  ('Fredericia', 'fredericia', 'furniture', 'verified', 3),
  ('Muuto', 'muuto', 'furniture', 'verified', 3),
  ('HAY', 'hay', 'furniture', 'verified', 3),
  ('&Tradition', '&tradition', 'furniture', 'verified', 3),
  ('Gubi', 'gubi', 'furniture', 'verified', 3),
  ('Normann Copenhagen', 'normann copenhagen', 'furniture', 'verified', 3),
  ('Audo Copenhagen', 'audo copenhagen', 'furniture', 'verified', 3),
  ('Montana', 'montana', 'furniture', 'verified', 3),
  ('String Furniture', 'string furniture', 'furniture', 'verified', 3),
  ('Skagerak', 'skagerak', 'furniture', 'verified', 3),
  ('Swedese', 'swedese', 'furniture', 'verified', 3),
  ('Mater', 'mater', 'furniture', 'verified', 3),
  ('Fogia', 'fogia', 'furniture', 'verified', 3),
  ('Eilersen', 'eilersen', 'furniture', 'verified', 3),
  ('BoConcept', 'boconcept', 'furniture', 'verified', 3),
  ('Bolia', 'bolia', 'furniture', 'verified', 3),
  ('Vipp', 'vipp', 'furniture', 'verified', 3),
  ('Stokke', 'stokke', 'furniture', 'verified', 3),
  ('Hans J. Wegner', 'hans j. wegner', 'furniture', 'verified', 3),
  ('Vitra', 'vitra', 'furniture', 'verified', 3),
  ('USM Haller', 'usm haller', 'furniture', 'verified', 3),
  ('Thonet', 'thonet', 'furniture', 'verified', 3),
  ('Walter Knoll', 'walter knoll', 'furniture', 'verified', 3),
  ('Rolf Benz', 'rolf benz', 'furniture', 'verified', 3),
  ('Interlübke', 'interlübke', 'furniture', 'verified', 3),
  ('COR', 'cor', 'furniture', 'verified', 3),
  ('Wittmann', 'wittmann', 'furniture', 'verified', 3),
  ('TEAM 7', 'team 7', 'furniture', 'verified', 3),
  ('e15', 'e15', 'furniture', 'verified', 3),
  ('ClassiCon', 'classicon', 'furniture', 'verified', 3),
  ('Tecta', 'tecta', 'furniture', 'verified', 3),
  ('Draenert', 'draenert', 'furniture', 'verified', 3),
  ('Hülsta', 'hülsta', 'furniture', 'verified', 3),
  ('Moooi', 'moooi', 'furniture', 'verified', 3),
  ('Leolux', 'leolux', 'furniture', 'verified', 3),
  ('Linteloo', 'linteloo', 'furniture', 'verified', 3),
  ('Pastoe', 'pastoe', 'furniture', 'verified', 3),
  ('Spectrum', 'spectrum', 'furniture', 'verified', 3),
  ('JNL', 'jnl', 'furniture', 'verified', 3),
  ('Ercol', 'ercol', 'furniture', 'verified', 3),
  ('G Plan', 'g plan', 'furniture', 'verified', 3),
  ('Linley', 'linley', 'furniture', 'verified', 3),
  ('Howe London', 'howe london', 'furniture', 'verified', 3),
  ('George Smith', 'george smith', 'furniture', 'verified', 3),
  ('Soho Home', 'soho home', 'furniture', 'verified', 3),
  ('OKA', 'oka', 'furniture', 'verified', 3),
  ('Andrew Martin', 'andrew martin', 'furniture', 'verified', 3),
  ('Julian Chichester', 'julian chichester', 'furniture', 'verified', 3),
  ('Porta Romana', 'porta romana', 'furniture', 'verified', 3),
  ('The Sofa & Chair Company', 'the sofa & chair company', 'furniture', 'verified', 3),
  ('Benchmark Furniture', 'benchmark furniture', 'furniture', 'verified', 3),
  ('Another Country', 'another country', 'furniture', 'verified', 3),
  ('SCP', 'scp', 'furniture', 'verified', 3),
  ('Vitsœ', 'vitsœ', 'furniture', 'verified', 3),
  ('Made.com', 'made.com', 'furniture', 'verified', 3),
  ('Heal''s', 'heal''s', 'furniture', 'verified', 3),
  ('Ligne Roset', 'ligne roset', 'furniture', 'verified', 3),
  ('Cinna', 'cinna', 'furniture', 'verified', 3),
  ('Liaigre', 'liaigre', 'furniture', 'verified', 3),
  ('Maison Sarah Lavoine', 'maison sarah lavoine', 'furniture', 'verified', 3),
  ('Caravane', 'caravane', 'furniture', 'verified', 3),
  ('Ralph Pucci', 'ralph pucci', 'furniture', 'verified', 3),
  ('Herman Miller', 'herman miller', 'furniture', 'verified', 3),
  ('Knoll', 'knoll', 'furniture', 'verified', 3),
  ('Baker', 'baker', 'furniture', 'verified', 3),
  ('Henredon', 'henredon', 'furniture', 'verified', 3),
  ('Holly Hunt', 'holly hunt', 'furniture', 'verified', 3),
  ('McGuire', 'mcguire', 'furniture', 'verified', 3),
  ('Bernhardt', 'bernhardt', 'furniture', 'verified', 3),
  ('Century Furniture', 'century furniture', 'furniture', 'verified', 3),
  ('Hickory Chair', 'hickory chair', 'furniture', 'verified', 3),
  ('Kindel', 'kindel', 'furniture', 'verified', 3),
  ('Stickley', 'stickley', 'furniture', 'verified', 3),
  ('Room & Board', 'room & board', 'furniture', 'verified', 3),
  ('Design Within Reach', 'design within reach', 'furniture', 'verified', 3),
  ('RH (Restoration Hardware)', 'rh (restoration hardware)', 'furniture', 'verified', 3),
  ('Maitland-Smith', 'maitland-smith', 'furniture', 'verified', 3),
  ('Theodore Alexander', 'theodore alexander', 'furniture', 'verified', 3),
  ('Emeco', 'emeco', 'furniture', 'verified', 3),
  ('Steelcase', 'steelcase', 'furniture', 'verified', 3),
  ('Haworth', 'haworth', 'furniture', 'verified', 3),
  ('Ethan Allen', 'ethan allen', 'furniture', 'verified', 3),
  ('Thomasville', 'thomasville', 'furniture', 'verified', 3),
  ('Mitchell Gold + Bob Williams', 'mitchell gold + bob williams', 'furniture', 'verified', 3),
  ('Crate & Barrel', 'crate & barrel', 'furniture', 'verified', 3),
  ('West Elm', 'west elm', 'furniture', 'verified', 3),
  ('Pottery Barn', 'pottery barn', 'furniture', 'verified', 3),
  ('CB2', 'cb2', 'furniture', 'verified', 3)
on conflict (category, normalized) do nothing;
