-- F45 W10 — Multi-tenancy step 2 (V4_0_1): NOT NULL the tenant_id (the V4_0_0 default backfilled
-- every existing + new row, so this is safe with no code change) + a per-table tenant_id index to
-- back the tenant filter the repo sweep adds. The DB default is intentionally kept until the sweep
-- finishes (it's the safety net); a later migration drops it once every insert sets tenant_id.

alter table approvals alter column tenant_id set not null;
alter table asset_events alter column tenant_id set not null;
alter table asset_groups alter column tenant_id set not null;
alter table asset_parties alter column tenant_id set not null;
alter table asset_quality_flags alter column tenant_id set not null;
alter table asset_valuation_snapshots alter column tenant_id set not null;
alter table assets alter column tenant_id set not null;
alter table audit_log_entries alter column tenant_id set not null;
alter table bank_transactions alter column tenant_id set not null;
alter table bills alter column tenant_id set not null;
alter table brand_usage alter column tenant_id set not null;
alter table budgets alter column tenant_id set not null;
alter table calendar_event_refs alter column tenant_id set not null;
alter table categories alter column tenant_id set not null;
alter table collection_members alter column tenant_id set not null;
alter table custom_field_definitions alter column tenant_id set not null;
alter table defects alter column tenant_id set not null;
alter table documents alter column tenant_id set not null;
alter table email_drafts alter column tenant_id set not null;
alter table email_messages alter column tenant_id set not null;
alter table email_threads alter column tenant_id set not null;
alter table employment_records alter column tenant_id set not null;
alter table entity_comments alter column tenant_id set not null;
alter table entity_documents alter column tenant_id set not null;
alter table entity_links alter column tenant_id set not null;
alter table export_jobs alter column tenant_id set not null;
alter table financial_accounts alter column tenant_id set not null;
alter table gl_accounts alter column tenant_id set not null;
alter table gl_transactions alter column tenant_id set not null;
alter table investment_lots alter column tenant_id set not null;
alter table locations alter column tenant_id set not null;
alter table mail_inboxes alter column tenant_id set not null;
alter table maintenance_plans alter column tenant_id set not null;
alter table net_worth_snapshots alter column tenant_id set not null;
alter table notification_subscriptions alter column tenant_id set not null;
alter table notifications alter column tenant_id set not null;
alter table payment_methods alter column tenant_id set not null;
alter table products alter column tenant_id set not null;
alter table properties alter column tenant_id set not null;
alter table receipts alter column tenant_id set not null;
alter table reconciliation_matches alter column tenant_id set not null;
alter table restore_jobs alter column tenant_id set not null;
alter table restructure_operations alter column tenant_id set not null;
alter table search_index alter column tenant_id set not null;
alter table shopping_lists alter column tenant_id set not null;
alter table tags alter column tenant_id set not null;
alter table task_projects alter column tenant_id set not null;
alter table tasks alter column tenant_id set not null;
alter table taxonomies alter column tenant_id set not null;
alter table users alter column tenant_id set not null;
alter table vendors alter column tenant_id set not null;
alter table wealth_entities alter column tenant_id set not null;

create index if not exists approvals_tenant_idx on approvals(tenant_id);
create index if not exists asset_events_tenant_idx on asset_events(tenant_id);
create index if not exists asset_groups_tenant_idx on asset_groups(tenant_id);
create index if not exists asset_parties_tenant_idx on asset_parties(tenant_id);
create index if not exists asset_quality_flags_tenant_idx on asset_quality_flags(tenant_id);
create index if not exists asset_valuation_snapshots_tenant_idx on asset_valuation_snapshots(tenant_id);
create index if not exists assets_tenant_idx on assets(tenant_id);
create index if not exists audit_log_entries_tenant_idx on audit_log_entries(tenant_id);
create index if not exists bank_transactions_tenant_idx on bank_transactions(tenant_id);
create index if not exists bills_tenant_idx on bills(tenant_id);
create index if not exists brand_usage_tenant_idx on brand_usage(tenant_id);
create index if not exists budgets_tenant_idx on budgets(tenant_id);
create index if not exists calendar_event_refs_tenant_idx on calendar_event_refs(tenant_id);
create index if not exists categories_tenant_idx on categories(tenant_id);
create index if not exists collection_members_tenant_idx on collection_members(tenant_id);
create index if not exists custom_field_definitions_tenant_idx on custom_field_definitions(tenant_id);
create index if not exists defects_tenant_idx on defects(tenant_id);
create index if not exists documents_tenant_idx on documents(tenant_id);
create index if not exists email_drafts_tenant_idx on email_drafts(tenant_id);
create index if not exists email_messages_tenant_idx on email_messages(tenant_id);
create index if not exists email_threads_tenant_idx on email_threads(tenant_id);
create index if not exists employment_records_tenant_idx on employment_records(tenant_id);
create index if not exists entity_comments_tenant_idx on entity_comments(tenant_id);
create index if not exists entity_documents_tenant_idx on entity_documents(tenant_id);
create index if not exists entity_links_tenant_idx on entity_links(tenant_id);
create index if not exists export_jobs_tenant_idx on export_jobs(tenant_id);
create index if not exists financial_accounts_tenant_idx on financial_accounts(tenant_id);
create index if not exists gl_accounts_tenant_idx on gl_accounts(tenant_id);
create index if not exists gl_transactions_tenant_idx on gl_transactions(tenant_id);
create index if not exists investment_lots_tenant_idx on investment_lots(tenant_id);
create index if not exists locations_tenant_idx on locations(tenant_id);
create index if not exists mail_inboxes_tenant_idx on mail_inboxes(tenant_id);
create index if not exists maintenance_plans_tenant_idx on maintenance_plans(tenant_id);
create index if not exists net_worth_snapshots_tenant_idx on net_worth_snapshots(tenant_id);
create index if not exists notification_subscriptions_tenant_idx on notification_subscriptions(tenant_id);
create index if not exists notifications_tenant_idx on notifications(tenant_id);
create index if not exists payment_methods_tenant_idx on payment_methods(tenant_id);
create index if not exists products_tenant_idx on products(tenant_id);
create index if not exists properties_tenant_idx on properties(tenant_id);
create index if not exists receipts_tenant_idx on receipts(tenant_id);
create index if not exists reconciliation_matches_tenant_idx on reconciliation_matches(tenant_id);
create index if not exists restore_jobs_tenant_idx on restore_jobs(tenant_id);
create index if not exists restructure_operations_tenant_idx on restructure_operations(tenant_id);
create index if not exists search_index_tenant_idx on search_index(tenant_id);
create index if not exists shopping_lists_tenant_idx on shopping_lists(tenant_id);
create index if not exists tags_tenant_idx on tags(tenant_id);
create index if not exists task_projects_tenant_idx on task_projects(tenant_id);
create index if not exists tasks_tenant_idx on tasks(tenant_id);
create index if not exists taxonomies_tenant_idx on taxonomies(tenant_id);
create index if not exists users_tenant_idx on users(tenant_id);
create index if not exists vendors_tenant_idx on vendors(tenant_id);
create index if not exists wealth_entities_tenant_idx on wealth_entities(tenant_id);
