kanzen {
  env = "local"
  env = ${?KANZEN_ENV}
  port = 8080
  port = ${?PORT}
  admin-port = 9990
  admin-port = ${?ADMIN_PORT}
  metrics-port = 9464
  metrics-port = ${?METRICS_PORT}
  db {
    url = "jdbc:postgresql://localhost:5432/kanzen"
    url = ${?DATABASE_URL}
    user = "kanzen"
    user = ${?DB_USER}
    password = "kanzen"
    password = ${?DB_PASSWORD}
  }
}
